#!/bin/sh

# git_help: create a new private repository

if [ "$#" -ne 1 ]; then
	printf "%s" "usage: create_repo name" >&2
	exit 1
fi

REPO_PATH="/srv/git/${1%.git}.git"
mkdir -p "$REPO_PATH"
cd "$REPO_PATH"
git init --bare --shared
